import '../model/food_model.dart';

class FoodInfo {
  static List<FoodModel> drinksList = [
    FoodModel(
      id: 0,
      image: "lib/assets/lemon-mojito.jpg",
      name: "Lemon Mojito",
      price: "250",
      desc: "A refreshing citrusy drink with a hint of mint",
      star: 3,
      type: "Drink",
    ),
    FoodModel(
      id: 1,
      image: "lib/assets/strawberry-mojito.jpg",
      name: "Strawberry Mojito",
      price: "300",
      desc: "A fruity twist on the classic mojito with fresh strawberries",
      star: 4,
      type: "Drink",
    ),
    FoodModel(
      id: 2,
      image: "lib/assets/pepsi.jpg",
      name: "Pepsi",
      price: "100",
      desc: "Classic cola soda, always a favorite",
      star: 3,
      type: "Drink",
    ),
    FoodModel(
      id: 3,
      image: "lib/assets/sprite.jpg",
      name: "Sprite",
      price: "100",
      desc: "Refreshing lemon-lime soda, perfect for quenching your thirst",
      star: 3.9,
      type: "Drink",
    ),
    FoodModel(
      id: 4,
      image: "lib/assets/fanta.jpg",
      name: "Fanta",
      price: "80",
      desc: "Bright and bubbly orange soda, a burst of flavor",
      star: 3.2,
      type: "Drink",
    ),
  ];

  static List<FoodModel> supplementsList = [
    FoodModel(
      id: 0,
      image: "lib/assets/frites.jpg",
      name: "Frites",
      price: "150",
      desc: "Golden crispy French fries, perfect for dipping",
      star: 3.9,
      type: "Supplements",
    ),
    FoodModel(
      id: 1,
      image: "lib/assets/frites-souce.jpg",
      name: "Frites + Sauce fromage",
      price: "250",
      desc: "French fries served with delicious cheese sauce",
      star: 4.9,
      type: "Supplements",
    ),
    FoodModel(
      id: 2,
      image: "lib/assets/chicken.jpg",
      name: "Chicken Tenders",
      price: "400",
      desc: "Tender and juicy chicken strips, great for dipping",
      star: 3.5,
      type: "Supplements",
    ),
    FoodModel(
      id: 3,
      image: "lib/assets/egg.jpg",
      name: "Oeuf",
      price: "50",
      desc: "A simple yet tasty egg dish",
      star: 3,
      type: "Supplements",
    ),
    FoodModel(
      id: 4,
      image: "lib/assets/chess.jpg",
      name: "Gruyere",
      price: "80",
      desc: "Delicious Gruyere cheese, perfect for pairing",
      star: 4.1,
      type: "Supplements",
    ),
    FoodModel(
      id: 5,
      image: "lib/assets/chess1.jpg",
      name: "Comembert",
      price: "80",
      desc: "Creamy and flavorful Comembert cheese",
      star: 4.5,
      type: "Supplements",
    ),
  ];

  static List<FoodModel> burgerList = [
    FoodModel(
      id: 0,
      image: "lib/assets/burger1.jpg",
      name: "El pequeño",
      price: "280",
      desc: "Burger with 200g of meat and salad",
      star: 3.9,
      type: "Burger",
    ),
    FoodModel(
      id: 1,
      image: "lib/assets/burger2.jpg",
      name: "Classic Cheeseburger",
      price: "350",
      desc: "A timeless favorite with cheese and special sauce",
      star: 4,
      type: "Burger",
    ),
    FoodModel(
      id: 2,
      image: "lib/assets/burger3.jpg",
      name: "Spicy Jalapeño Burger",
      price: "320",
      desc: "For those who like it hot, with jalapeños and spicy mayo",
      star: 4.2,
      type: "Burger",
    ),
    FoodModel(
      id: 3,
      image: "lib/assets/burger4.jpg",
      name: "Mushroom Swiss Burger",
      price: "380",
      desc: "Loaded with sautéed mushrooms and Swiss cheese",
      star: 4.3,
      type: "Burger",
    ),
    FoodModel(
      id: 4,
      image: "lib/assets/burger5.jpg",
      name: "Veggie Delight Burger",
      price: "290",
      desc: "A meatless option with fresh veggies and veggie patty",
      star: 4.5,
      type: "Burger",
    ),
    FoodModel(
      id: 5,
      image: "lib/assets/burger6.jpg",
      name: "BBQ Bacon Burger",
      price: "410",
      desc: "Topped with crispy bacon and tangy BBQ sauce",
      star: 4.9,
      type: "Burger",
    ),
    FoodModel(
      id: 6,
      image: "lib/assets/burger7.jpg",
      name: "Double Trouble Burger",
      price: "420",
      desc: "Two juicy patties, double cheese, and all the fixings",
      star: 3.9,
      type: "Burger",
    ),
    FoodModel(
      id: 7,
      image: "lib/assets/burger8.jpg",
      name: "California Dream Burger",
      price: "360",
      desc: "Avocado, lettuce, and tomato for a taste of California",
      star: 4.2,
      type: "Burger",
    ),
    FoodModel(
      id: 8,
      image: "lib/assets/burger9.jpg",
      name: "Blue Cheese Burger",
      price: "370",
      desc: "Blue cheese crumbles and dressing for a rich flavor",
      star: 3.5,
      type: "Burger",
    ),
    FoodModel(
      id: 9,
      image: "lib/assets/burger10.jpg",
      name: "Fisherman's Catch Burger",
      price: "320",
      desc: "Fried fish fillet with tartar sauce and lettuce",
      star: 4.9,
      type: "Burger",
    ),
  ];
}
